// apps/desktop/src/renderer/src/components/ChatBubble.vue
<script setup lang="ts">
import { ref, computed } from 'vue'

const props = withDefaults(defineProps<{
  role?: 'user' | 'assistant'
  content?: string
  timestamp?: string
  recent?: boolean
  showCopy?: boolean
}>(), {
  role: 'assistant',
  recent: false,
  showCopy: true,
})

const copied = ref(false)
const containerRef = ref<HTMLDivElement>()

async function handleCopy() {
  try {
    const text = props.content || containerRef.value?.innerText || ''
    if (!text) return
    await navigator.clipboard.writeText(text)
    copied.value = true
    setTimeout(() => { copied.value = false }, 1600)
  } catch {
    // ignore
  }
}

const bubbleClasses = computed(() => [
  'relative px-4 py-3 rounded-xl max-w-xs lg:max-w-md',
  'transition-all duration-160 ease-out',
  props.role === 'user'
    ? 'themed-user-bubble text-white animate-slide-up'
    : 'glass-surface text-neutral-100 animate-slide-up',
  props.recent ? 'animate-pop-in' : '',
])
</script>

<template>
  <div :class="bubbleClasses">
    <div ref="containerRef" class="relative">
      <div
        :class="[
          'break-words text-sm whitespace-pre-wrap',
          showCopy ? 'pr-12' : '',
        ]"
      >
        <slot>{{ content }}</slot>
      </div>
      <button
        v-if="showCopy && content"
        :class="[
          'absolute top-1 right-1 text-xs px-2 py-1 rounded',
          'bg-neutral-800/80 hover:bg-neutral-700 backdrop-blur-sm',
          'transition-all duration-200',
        ]"
        @click="handleCopy"
      >
        {{ copied ? 'Copied' : 'Copy' }}
      </button>
    </div>
    <p
      v-if="timestamp"
      :class="[
        'text-xs mt-1',
        role === 'user' ? 'text-primary-200' : 'text-neutral-500',
      ]"
    >
      {{ timestamp }}
    </p>
  </div>
</template>

// apps/desktop/src/renderer/src/components/ChatBubble.tsx
import React, { useState, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

type Props = {
  id?: string
  role?: 'user' | 'assistant'
  content: React.ReactNode
  timestamp?: string
  recent?: boolean
  showCopy?: boolean
}

export default function ChatBubble({ role = 'assistant', content, timestamp, recent = false, showCopy = true }: Props) {
  const [copied, setCopied] = useState(false)
  const containerRef = useRef<HTMLDivElement | null>(null)

  const handleCopy = async () => {
    try {
      // Prefer explicit text if available, otherwise use the rendered text content
      const text = typeof content === 'string' ? content : (containerRef.current?.innerText || '')
      if (!text) return
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 1600)
    } catch (e) {
      // ignore
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      whileHover={{ scale: 1.02 }}
      transition={{ type: 'spring', stiffness: 300 }}
      className={`msg-bubble ${role === 'user' ? 'user' : ''} ${recent ? 'recent' : ''} max-w-xs lg:max-w-md px-4 py-3 rounded-xl`}
    >
      <div style={{ position: 'relative' }} ref={containerRef}>
        <div className="break-words text-sm" style={{ whiteSpace: 'pre-wrap', paddingRight: '48px' }}>{content}</div>
        {showCopy !== false && (
          <>
            <button onClick={handleCopy} aria-label="Copy message" className="absolute top-2 right-2 text-xs bg-neutral-800 hover:bg-neutral-700 px-2 py-1 rounded opacity-90">{copied ? 'Copied' : 'Copy'}</button>
            <AnimatePresence>
              {copied && (
                <motion.span className="copy-toast" initial={{ opacity: 0, y: -6, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1.02 }} exit={{ opacity: 0, y: -6, scale: 0.96 }} transition={{ duration: 0.45 }}>
                  Copied
                </motion.span>
              )}
            </AnimatePresence>
          </>
        )}
      </div>

      {timestamp ? <p className={`text-xs mt-1 ${role === 'user' ? 'text-indigo-200' : 'text-neutral-500'}`}>{timestamp}</p> : null}
    </motion.div>
  )
}
